### ISSUE TITLE
Question about using Git branches and tags

### ISSUE THREAD

**Issue by DavidPesta** [RaiMan/SikuliX2#1]
This project is extremely awesome. Thank you so much for picking up the development of this.

I was just wondering. What is the reason for creating a separate project repository for each new version for every year of development? Isn't it easier to coordinate versions in the same repository using Git branches and mark releases in Git tags? That way, we can follow development without needing to fork and clone a new repository every year and our GitHub discussions can remain focused in one repository instead of spread out across multiple projects.

You may have reasons that outweigh these thoughts. Just curious. Thanks again!

**Comment by RaiMan** [comment]
Thanks for feedback.

You are absolutely right.

But I decided to start a new repo, because I want to completely restructure the stuff and keep the version 1.1 like some LTS version with maybe some 1.1.x bug fix updates every some month together with some feature updates downgraded from 1.2.

The 2014 stuff will be the last version, that is compilable with Java 6.

With the new repo I will do some experimenting the next months in different directions.
I just wanted to keep this buzz apart from the "stable" stuff of version 1.1

One of these "experiments" will affect the repo itself (git-subprojects, ...).

... so I thought it would be better, to start a new road.

So thanks for your comment: I guess I give the repo another name, since I do not plan, to start a new one every year in the future.

... and I guess I will name it version 2.0 ;-)

**Comment by DavidPesta** [comment]
Sounds good, keep up the great work! Such an important project!

**Comment by nschle85** [comment]
I think its a bad idea to cut the whole history.

**Comment by DavidPesta** [comment]
@nschle85 - No, the developer is doing the right thing. He is completely restructuring everything from the beginning for a version 2.0 and he believes the code can benefit from this. He's starting a blank slate and slowly adding a new foundation for a new structure and then migrating the old code into it. That really does make it a new project from a code perspective. You don't want a completely disjointed history in the same repository. You really do want a new repository for this.

@RaiMan - Keep up the great work!
