### ISSUE TITLE
ImageFinder not working on Amazon EC2 Ubuntu 14.04

### ISSUE THREAD

**Issue by Hassan-Radi** [RaiMan/SikuliX2#22]
Hello,

I am using Sikuli to do some template matching as a part of some TestNG test and It is working just fine locally on my Macbook, but whenever I try to run the same code on the Jenkins server (Headless server running on Amazon EC2 instance), it fails with the following details:
> java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat()J

What I did so far:
- I followed your instructions on getting Sikuli working on Linux-based OSes here: http://sikulix.com/specials/files/linux-setup-prerequisites.html.
- I also tried building OpenCV from the source and pointing to the build libs directory.

Can you help me identify what is going on? Am I doing something wrong? 

**Environment details:**
OS: Ubuntu 14.04
Arch: x64
Sikuli version: 1.1.1-SNAPSHOT

**Comment by robertbarnard** [comment]
Dear Hassan-Radi,

I'm new to this domain, but very interested.

Apparently there is a difference between how Apple's JVM and and Oracle's JVM load native
library files, this item may be of interest to you: http://grokbase.com/t/gg/play-framework/137fc154cy/how-to-load-native-library-unsatisfiedlinkerror

Also along another thought-line, did you build OpenCV on both (Apple and Linux) platforms, and it worked on Apple as well?

The reason I ask is because when I read this thread (http://code.opencv.org/issues/3077), it occurred to me you may be working with a mismatched. But I think the Linux OS isn't properly linking the library, as outlined in the first article (above).

I hope these suggestions save you some time in finding a solution.

Best Regards,
Robert

**Comment by Hassan-Radi** [comment]
Dear @robertbarnard :

Thank you so much for your reply. Those are actually very good points and I am surprised I haven't considered them :smile: I will investigate more about this tomorrow and get back to you.

Hassan

**Comment by Hassan-Radi** [comment]
@robertbarnard: I gave it a try today and still no luck. 

I think one of the road-map items for version 2 is to remove dependency on native elements and completely revamp this part into a purely java implementation, so hypothetically speaking if we managed to do this, the problem I am having would get fixed. 

I am not sure how complicated the code is or how much work is needed to get such feature done, but I am personally gonna look for other solutions to this problem and I might end up writing my own code to do this part. I will keep you updated about it.

In the meantime, I'd really appreciate it if anyone would provide me with insights or possible workarounds to this issue.

Thanks in advance.
Hassan

**Comment by RaiMan** [comment]
@Hassan-Radi 
Your problems have nothing to do with wether code against the OpenCV API is written in Java or C++. In both cases you need to prepare the respective OpenCV libraries to be available to the loader at runtime. On Mac and Windows this is solved by the bundled library versions. On Linux systems it is not possible to bundle libraries accepted on all Linux flavours. Version 1.1.1 has a library version bundled, that should work on Ubuntu systems >12.xx.

For SikuliX the availability of an OpenCV Java API  simply makes it possible to avoid the extra layer of C++ code. Hence trying to implement your own solution, does not help with this library problem.

To track down your specific problem, the setup log might reveal some information. Another option is to run the stuff with Java option -Dsikuli.debug=3, to get more information about the startup steps.

And of course it  might be possible, that you have provided the correct OpenCV libraries, but they are not found or accepted at runtime of SikuliX.

**Comment by Hassan-Radi** [comment]
@RaiMan:
First of all, thanks for your reply.
I think I misunderstood your road-map for version 2.0, I thought you were going to remove dependency on OpenCV and replace it with a pure Java implementation to solve such problems with native support for C++ libraries.

Anyway I was able to solve my problem by using BoofCV and optimising the code a little bit to run faster. I had to move to a different solution, because I really needed things to work from the Jenkins side and I wasted a lot of time researching and trying to solve the problem I was having. You know how bad it can get with deadlines 😭 .

Thanks a lot for your support guys and wish you the best of luck!
Hassan

**Comment by RaiMan** [comment]
@Hassan-Radi 
Thanks for your feedback.

I had a short look on BoofCV and decided to stay with OpenCV.

The library problem is dramatically reduced with version 2, since either the bundled library for Ubuntu 64Bit works or can easily (rather ;-) be built from sources, if the package system of the Linux version does not provide a suitable package.
Version 2 builds and works on TravisCI on an Ubuntu 12 with xvfb.

Deadlines: I feel with you and fully understand - I am glad to not really have them with SikuliX (at least not given from someone else).

All the best to you also.
Raimund aka RaiMan.

**Comment by RaiMan** [comment]
I close this issue here now, because it relates actually to version 1.1.x
