### ISSUE TITLE
Quick Question: Why was Java Chosen ?

### ISSUE THREAD

**Issue by GuacheSuede** [RaiMan/SikuliX2#28]

**Comment by RaiMan** [comment]
To keep it as upward compatible as possible.

The history of Sikuli(X) started in 2009 ;-)
Java was chosen by the original developers.
... and besides Python it fits with the integration of OpenCV.

What would have been your favorite?

**Comment by GuacheSuede** [comment]
Thanks for asking me :). I have always been interested in Sikuli as a software(or things like it) and personally would have written it in C++ mostly due to the memory savings and to run it on low energy machines. Which was why i asked in the first place, was thinking of writing something along the lines as such but sticking to C++.

**Comment by RaiMan** [comment]
Looking from the core features of SikuliX using C++ is surely a good choice also with respect to OpenCV and Tesseract. 
But the integration into higher level programming languages and scripting environments would always need some extra efforts compared to SikuliX being a Java library and tool.
On the other hand I do not really understand the need for SikuliX running directly on such low profile machines (like e.g. a Raspberry ???), since a simple vnc-solution should be sufficient.

**Comment by GuacheSuede** [comment]
I see, thanks for the explanation :+1:

**Comment by GuacheSuede** [comment]
What would the differences be between SikuliX2 and 1 ?

**Comment by RaiMan** [comment]
Watch out ;-)
I will start with more information after mid Jan. 2018

**Comment by GuacheSuede** [comment]
I sure will do :)

**Comment by GuacheSuede** [comment]
If you do not mind answering, how does SIkuli connect to the VNC server such as Tiger VNC, is there a specific file one should look at ?

**Comment by RaiMan** [comment]
the vnc client support can be found in the working form in SikuliX 1.1.1 in
https://github.com/RaiMan/SikuliX-2014
in the module sikuliapi (folder API) in the Java package org.sikuli.vnc
the docs: http://sikulix-2014.readthedocs.io/en/latest/screen.html#connecting-to-a-vnc-server-vncscreen

In version 2 I decided to have a more compact design: a combination of the ability to show something and allow the user to type text and use a mouse (or equivalent) is a device.
Hence in version 2 the stuff is in com.sikulix.devices (still under construction).
